CREATE DATABASE HierarchyManager;
USE HierarchyManager;

CREATE TABLE NodeActions
(
	NodeActionID	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NodeActionName	NVARCHAR(20) NOT NULL
);

CREATE TABLE FileActions
(
	FileActionID	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	FileActionName	NVARCHAR(20) NOT NULL
);

CREATE TABLE FileExtensions
(
	ExtensionID	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Mask		NVARCHAR(12) NOT NULL,
	Extension	NVARCHAR(80) NOT NULL
);

CREATE TABLE Nodes
(
	NodeID		INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NodeName	NVARCHAR(20) NOT NULL,
	UserID		INT UNSIGNED NOT NULL,
	IsShared	BIT NOT NULL
);

CREATE TABLE Users
(
	UserID		INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	LoginWord	NVARCHAR(20) NOT NULL,
	PassPhrase	NVARCHAR(20) NOT NULL,
	FirstName	NVARCHAR(20),
	LastName	NVARCHAR(20),
	RootNodeID	INT UNSIGNED,
	CONSTRAINT FOREIGN KEY (RootNodeID) REFERENCES Nodes(NodeID)
);

ALTER TABLE Nodes ADD CONSTRAINT FOREIGN KEY (UserID) REFERENCES Users(UserID);

CREATE TABLE Edges
(
	EdgeID		INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ChildID		INT UNSIGNED NOT NULL,
	ParentID	INT UNSIGNED NOT NULL,
	UserID		INT UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (ChildID) REFERENCES Nodes(NodeID),
	CONSTRAINT FOREIGN KEY (ParentID) REFERENCES Nodes(NodeID),
	CONSTRAINT FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE NodesLog
(
	NodesLogID		INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NodeActionID	INT UNSIGNED NOT NULL,
	NodeID			INT UNSIGNED NOT NULL,
	UserID			INT UNSIGNED NOT NULL,
	ActionTimeStamp	DATETIME NOT NULL,
	CONSTRAINT FOREIGN KEY (NodeActionID) REFERENCES NodeActions(NodeActionID),
	CONSTRAINT FOREIGN KEY (NodeID) REFERENCES Nodes(NodeID),
	CONSTRAINT FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Files
(
	FileID		INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Name		NVARCHAR(20) NOT NULL,
	ExtensionID INT UNSIGNED NOT NULL,
	FileData	BLOB,
	IsShared	BIT NOT NULL,
	CONSTRAINT FOREIGN KEY (ExtensionID) REFERENCES FileExtensions(ExtensionID)
);

CREATE TABLE FilesLog
(
	FilesLogID		INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Field			INT UNSIGNED NOT NULL,
	UserID			INT UNSIGNED NOT NULL,
	FileActionID	INT UNSIGNED NOT NULL,
	ActionTimeStamp	DATETIME NOT NULL,
	CONSTRAINT FOREIGN KEY (Field) REFERENCES Files(FileID),
	CONSTRAINT FOREIGN KEY (UserID) REFERENCES Users(UserID),
	CONSTRAINT FOREIGN KEY (FileActionID) REFERENCES FileActions(FileActionID)
);

CREATE TABLE NodeFiles
(
	NodeID	INT UNSIGNED NOT NULL,
	FileID	INT UNSIGNED NOT NULL,
	PRIMARY KEY (NodeID, FileID),
	CONSTRAINT FOREIGN KEY (NodeID) REFERENCES Nodes(NodeID),
	CONSTRAINT FOREIGN KEY (FileID) REFERENCES Files(FileID)
);

CREATE TABLE Ratings
(
	UserID	INT UNSIGNED NOT NULL,
	FileID	INT UNSIGNED NOT NULL,
	Value	INT UNSIGNED NOT NULL,
	PRIMARY KEY (UserID, FileID),
	CONSTRAINT FOREIGN KEY (UserID) REFERENCES Users(UserID),
	CONSTRAINT FOREIGN KEY (FileID) REFERENCES Files(FileID)
);

CREATE TABLE Comments
(
	CommentID	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	UserID		INT UNSIGNED NOT NULL,
	FileID		INT UNSIGNED NOT NULL,
	CommentText	NVARCHAR(800) NOT NULL,
	CONSTRAINT FOREIGN KEY (UserID) REFERENCES Users(UserID),
	CONSTRAINT FOREIGN KEY (FileID) REFERENCES Files(FileID)
);
